export function DevelopmentSandboxBanner() {
  return (
    <div style={{ backgroundColor: '#fef3c7', borderBottom: '1px solid #f59e0b', padding: '12px 24px', color: '#b45309' }}>
      <div style={{ maxWidth: '1200px', margin: '0 auto', fontSize: '14px', fontWeight: 500 }}>
        ⚠️ <strong>Demo Data Notice:</strong> Entries in this dashboard are periodically generated by an automated script using synthetic/randomized values — they do not represent real user submissions. This system is fully functional; try the live upload above to generate real results.
      </div>
    </div>
  );
}
